version: '3.4'

services:
  aspnetcorethingsserver:
    image: ${DOCKER_REGISTRY}aspnetcorethingsserver
    build:
      context: .
      dockerfile: AspNetCoreThingsServer/Dockerfile

  angularclient:
    image: ${DOCKER_REGISTRY}angularclient
    build:
      context: .
      dockerfile: AngularClient/Dockerfile
